### ISSUE TITLE
Cannot download minecraft.

### ISSUE THREAD

**Issue by sajjaadf** [dscalzi/HeliosLauncher#117]
![image](https://user-images.githubusercontent.com/32078755/93266345-c1e1ab00-f75e-11ea-9839-1e73b4c082a5.png)

**Comment by sajjaadf** [comment]
![image](https://user-images.githubusercontent.com/32078755/93266366-cd34d680-f75e-11ea-8103-cce7451a2258.png)

**Comment by dscalzi** [comment]
http://resources.download.minecraft.net/ is online, download is working as expected for me. Are you connected to the internet..?

**Comment by sajjaadf** [comment]
yes I am, everything else downloads fine, but this was built from source, with only a custom distribution.json, made with Nebula, which ill link at [http://play.theend.link/files/distribution.json](http://play.theend.link/files/distribution.json)

`{
  "version": "1.0.0",
  "rss": "",
  "discord": {
    "clientId": "12334567890123456789",
    "smallImageText": "the End Network",
    "smallImageKey": "seal-circle"
  },
  "servers": [
    {
      "id": "theEndNetwork-1.15.2",
      "name": "The End Network",
      "description": "The End Network Hub (1.15.2)",
      "icon": null,
      "version": "0.1.3",
      "address": "play.theend.link:25565",
      "minecraftVersion": "1.15.2",
      "discord": null,
      "mainServer": true,
      "autoconnect": true,
      "modules": []
    }
  ]
}
`

**Comment by sajjaadf** [comment]
@dscalzi

**Comment by dscalzi** [comment]
Can you try setting this to `https`? https://github.com/dscalzi/HeliosLauncher/blob/master/app/assets/js/assetguard.js#L1334

Not sure why this isnt working for you. Maybe that?

**Comment by dscalzi** [comment]
https://github.com/dscalzi/HeliosLauncher/commit/3ea41b42e5b4c8fd1f4b813301b3a4813cc40601
