### ISSUE TITLE
Custom 1.15.2 Dist.json unable to work.

### ISSUE THREAD

**Issue by sajjaadf** [dscalzi/HeliosLauncher#118]
![image](https://user-images.githubusercontent.com/32078755/93266345-c1e1ab00-f75e-11ea-9839-1e73b4c082a5.png)

its a custom distribution.json, made with Nebula, which ill link at [http://play.theend.link/files/distribution.json](http://play.theend.link/files/distribution.json) Most of the assets download, but it gets stuck at 76% and then errors out.

`{
  "version": "1.0.0",
  "rss": "",
  "discord": {
    "clientId": "12334567890123456789",
    "smallImageText": "the End Network",
    "smallImageKey": "seal-circle"
  },
  "servers": [
    {
      "id": "theEndNetwork-1.15.2",
      "name": "The End Network",
      "description": "The End Network Hub (1.15.2)",
      "icon": null,
      "version": "0.1.3",
      "address": "play.theend.link:25565",
      "minecraftVersion": "1.15.2",
      "discord": null,
      "mainServer": true,
      "autoconnect": true,
      "modules": []
    }
  ]
}
`

**Comment by sajjaadf** [comment]
resolved with proper libraries at [http://play.theend.link/distribution.json ](http://play.theend.link/distribution.json )

**Comment by sajjaadf** [comment]
closed

**Comment by sajjaadf** [comment]
nope, even with all the forge libraries, it still errors out

**Comment by dscalzi** [comment]
Duplicate https://github.com/dscalzi/HeliosLauncher/issues/117. See my comment there.

**Comment by sajjaadf** [comment]
@dscalzi "download is working as expected for me. Are you connected to the internet..?" yes, as im able to connect to it as well when entered in a browser url
