### ISSUE TITLE
Cannot build win dist

### ISSUE THREAD

**Issue by sajjaadf** [dscalzi/HeliosLauncher#119]
![image](https://user-images.githubusercontent.com/32078755/93398137-dc378980-f82f-11ea-97b3-f70bf2c31411.png)
error when running `$ npm run dist:win`

**Comment by dscalzi** [comment]
![image](https://user-images.githubusercontent.com/9703873/93398580-d5b60b80-f849-11ea-94fb-ede36dc1d318.png)
