### ISSUE TITLE
SRV Record Ping for Server Status Checker

### ISSUE THREAD

**Issue by ColaIan** [dscalzi/HeliosLauncher#120]
Feature request as title, thanks :D

**Comment by dscalzi** [comment]
@ColaIan do you have a srv ip I could use to test? You can DM me on discord if you want.

**Comment by dscalzi** [comment]
Support added in https://github.com/dscalzi/helios-core/commit/19a3dccb9fbeba9559104c8978fa978536bcc05f, it will be available once #270 is merged.
