### ISSUE TITLE
MC 1.8.9 loading bug

### ISSUE THREAD

**Issue by splatboydev** [dscalzi/HeliosLauncher#122]
https://gist.github.com/splatboy20081/a43628b9f28526fa19905a60cf069deb is my dist JSON, it keeps on crashing because of "mercurius_updater"??

I have not added a 'mercurial_updater' mod
![image](https://user-images.githubusercontent.com/64037464/97948139-7d2cc600-1d44-11eb-956d-45d631e65986.png)

**Comment by splatboy20081** [comment]
also do you have a 1.8.9 launchwrapper JAR on the site? I can't find one

**Comment by GeekCornerGH** [comment]
Just use[https://GitHub.com/dscalzi/nebula](Nebula) 🙂

**Comment by splatboy20081** [comment]
aight thx
