### ISSUE TITLE
Support for Microsoft accounts?

### ISSUE THREAD

**Issue by 42A7C5** [dscalzi/HeliosLauncher#131]
I just bought the game on my Microsoft account and am looking to set up the launcher. However, it's asking me to log in with my Mojang info. Is there any way I can play on the Helios servers?

**Comment by dscalzi** [comment]
Support for microsoft accounts is in progress. Brand new accounts will not be able to login just yet.

**Comment by DrDeee** [comment]
Perhaps [this](https://github.com/PrismarineJS/node-minecraft-protocol) could help. It already supports logging in with Microsoft, even without a proxy.

**Comment by 1ost** [comment]
any idea when this is coming?

**Comment by NhProGamer** [comment]
[Look this :)](https://github.com/ModRealms/ModRealmsLauncher)

**Comment by SNDST00M** [comment]
Correction - https://github.com/ModRealms/ModRealmsLauncher/blob/v2.5.1-release/app/assets/js/microsoft.js

**Comment by dscalzi** [comment]
Closing in favor of #210
