### ISSUE TITLE
How to make distribution.json without any mods

### ISSUE THREAD

**Issue by Izurumn** [dscalzi/HeliosLauncher#133]
Have any idea to make distribution.json without any mods with 1.16.2 version?

**Comment by Max-Oe** [comment]
npm run start -- g server SERVERNAME 1.16.4

npm run start --g distro

Use Nebula.
https://github.com/dscalzi/Nebula

**Comment by dscalzi** [comment]
You need forge, vanilla launch is not supported.

**Comment by coeragames** [comment]
You can use it with any mods, but running with Forge.
You will still be able to login in Vanilla/Spigot servers, but client will be in Forge.

Hope it can help you !

**Comment by Izurumn** [comment]
![image](https://user-images.githubusercontent.com/12643171/103712159-089c2f00-4ff4-11eb-87e1-18334f87a85a.png)
It seems I can't generate it. 
Can you generate for me?

**Comment by Max-Oe** [comment]
As he said correct Vanilla is not supported therefor you need to use following commands: 

 npm run start -- g server SERVERNAME 1.16.4 --forge 

npm run start --g distro

**Comment by Izurumn** [comment]
![image](https://user-images.githubusercontent.com/12643171/103712850-d2f84580-4ff5-11eb-83f9-a5a3a786b0cf.png)
Still got error, can you do it for me? 
I want example of it.
Thanks.

**Comment by Max-Oe** [comment]
```

{
  "version": "1.0.0",
  "rss": "<LINK TO RSS FEED>",
  "discord": {
    "clientId": "<FILL IN OR REMOVE DISCORD OBJECT>",
    "smallImageText": "<FILL IN OR REMOVE DISCORD OBJECT>",
    "smallImageKey": "<FILL IN OR REMOVE DISCORD OBJECT>"
  },
  "servers": [
    {
      "id": "MyServer-1.16.4",
      "name": "MyServer (Minecraft 1.16.4)",
      "description": "MyServer Running Minecraft 1.16.4",
      "icon": null,
      "version": "1.0.0",
      "address": "localhost:25565",
      "minecraftVersion": "1.16.4",
      "discord": {
        "shortId": "<FILL IN OR REMOVE DISCORD OBJECT>",
        "largeImageText": "<FILL IN OR REMOVE DISCORD OBJECT>",
        "largeImageKey": "<FILL IN OR REMOVE DISCORD OBJECT>"
      },
      "mainServer": false,
      "autoconnect": false,
      "modules": []
    }
  ]
}
```

**Comment by Izurumn** [comment]
How do I find these .jar files?

**Comment by dscalzi** [comment]
Node 14...
