### ISSUE TITLE
Rss flux for News

### ISSUE THREAD

**Issue by OrgeAlexj06** [dscalzi/HeliosLauncher#140]
Hello, I am here to advise you to change something : the rss feed for news is becoming a handicap because it is almost nowhere to be found. You will have to change this system to a more modern one to improve the launcher the most. Thank you. If not, do you have another solution to make an rss feed ?
Good night

**Comment by GeekCornerGH** [comment]
Just use Xenforo, WordPress or Ghost...

**Comment by norhu1130** [comment]
Wix Blog!

**Comment by GeekCornerGH** [comment]
Honnestly, Wix is not designed to make blogs. Just static webpages

**Comment by Alexandre88295** [comment]
Good evening,
Except I don't know how to create one and how to send it to the server. Thank you for helping me ;)

**Comment by OrgeAlexj06** [comment]
Good evening,
Except I don't know how to create one and how to send it to the server. Thank you for helping me ;)

**Comment by DrDeee** [comment]
@OrgeAlexj06
Take a look at [this](https://rss.app/), it may help you.

**Comment by dscalzi** [comment]
The RSS feed is a very simple parser maintained in-house. It targets the RSS format that was used on the WesterosCraft forum a couple of years ago. If you want to pull news from a different format, it is as easy as rewriting this method https://github.com/dscalzi/HeliosLauncher/blob/master/app/assets/js/scripts/landing.js#L1088 .
