### ISSUE TITLE
Not detecting "Releases"/updates in the launcher.

### ISSUE THREAD

**Issue by ThaNightHawk** [dscalzi/HeliosLauncher#145]
First of all, thank you for your work, it's an amazing platform to expand on.

I have a question about the updates/automatic updates.
- I've done some test-releases, matching versionnumbers, but I cannot get the launcher to detect a newer version released.

I'm sitting with a v5.0.0 client on my laptop, while having a v6.0.0 version release on GitHub, but no prompt about updates in the client.

I'm not sure about, what could be wrong.

**Comment by coeragames** [comment]
Did you compiled with Travis (by having a draft release before the build was completed) ?
Did you put vx.x on the release.
And is the version matching in package.json and on the release ?

**Comment by DrDeee** [comment]
> And is the version matching in package.json and on the release ?
in package.json (as example) 1.2.3, as tag on github **v**1.2.3

**Comment by coeragames** [comment]
> > And is the version matching in package.json and on the release ?
> 
> in package.json (as example) 1.2.3, as tag on github **v**1.2.3

Exactly :)

**Comment by Phasfeldt** [comment]
> Did you compiled with Travis (by having a draft release before the build was completed)? 
I have no tried this, no - Gonna give it a try ASAP and get back to you. 

> Did you put vx.x on the release.
Yes, multiple times. 

> And is the version matching in package.json and on the release ?
Yes, I've tried that, launcher still not detecting it. 

Another question: Do you need to build for both Linux, Mac and Windows for it to pickup on it, or is one system enough?

**Comment by DrDeee** [comment]
Only one os is enough, but if you're using an ci like travis or github actions, building installers for all os is not difficult.

And don't forge to include the latest[-<os>].yml into the release artifacts, that was my first issue.

**Comment by Phasfeldt** [comment]
> Only one os is enough, but if you're using an ci like travis or github actions, building installers for all os is not difficult.
> 
> And don't forge to include the latest[-<os>].yml into the release artifacts, that was my first issue.

I tried that, didn't solve it :(

> **EDIT**
> Can't see v6.0.0 release on your fork.

I removed it, and didn't get around to redo the test release. - Doing one right now

**Comment by Phasfeldt** [comment]
I figured it out. Apparently TravisCI renamed the windows launcher to "Name.Launcher" instead of "namelauncher", so it didn't pick up the update in the code, as it looked for "namelauncher" and not "Name.Launcher".

TravisCI now correctly names the files, and the problem is gone.
Summary: TravisCI was the problem, not the HeliosLauncher base.
