### ISSUE TITLE
add another server

### ISSUE THREAD

**Issue by therisen13** [dscalzi/HeliosLauncher#149]
hello,

i wanted to ask if you can add another server to the launcher?
I occassionaly visit ArdaCraft but usually join my own server on an older MC version.
how can I add it to the list?

thank you very much and excuse me if this is the wrong place to post.

**Comment by dscalzi** [comment]
It sounds like you're using ArdaCraft's launcher which is a modified version of Helios. Unfortunately there is no way to do this currently as the distribution can only be modified by the network that distributes the launcher.
