### ISSUE TITLE
Pack specific ram

### ISSUE THREAD

**Issue by Bennyboy1695** [dscalzi/HeliosLauncher#154]
A nice option would be if each pack could specify its own ram amount for the case where one pack is more ram hungry then the rest you can just have that pack allow more ram to be used

**Comment by dscalzi** [comment]
Pack-specific settings would be nice, but unfortunately that requires a non-trivial rework to the settings system.

**Comment by dscalzi** [comment]
Will be added with #270

**Comment by dscalzi** [comment]
https://github.com/dscalzi/HeliosLauncher/pull/270/commits/a731fa90ea300e156eaf7c026a8a93036a5aec98
