### ISSUE TITLE
Server IP

### ISSUE THREAD

**Issue by AndusDEV** [dscalzi/HeliosLauncher#155]
How to change server ip? in what file is it?

**Comment by DrDeee** [comment]
@AndusDEV
You need to create a separate distribution.json for your launcher. You can either do this with [Nebula](https://github.com/dscalzi/Nebula), or [write it yourself](https://github.com/dscalzi/HeliosLauncher/blob/master/docs/distro.md).

You have to host this distribution.json and all required files on some webserver and add the URL to /app/assets/js/distromanager.js line 540.
