### ISSUE TITLE
Launcher stops at 100% prepairing to launch/how to add offline support, still having online login

### ISSUE THREAD

**Issue by AndusDEV** [dscalzi/HeliosLauncher#156]
I've edited code a little (only changed some mods, ip address, and changed language) and now it stops at 100% prepairing to launch. Help, please?

**Comment by GeekCornerGH** [comment]
This is a known bug, just restart your launcher 😁

**Comment by AndusDEV** [comment]
Yeah I've restarted it maybe 2 times. And it still don't working

**Comment by AndusDEV** [comment]
Oh. And how could i make it offline? (If there is even some option to do it, but still with premium support)

**Comment by Aeris1One** [comment]
There's no option for offline mode and dscalzi already said countless time that there will never be one
