### ISSUE TITLE
Need to Login again when several windows opened

### ISSUE THREAD

**Issue by coeragames** [dscalzi/HeliosLauncher#160]
Hello !

I'm opening this issue because I noticed there's a bug when you open several windows of the launcher, at the same time: you need to login again. 

And it's really annoying to login again when you click several times on open the launcher.

Here's the console log: https://pastebin.com/aTzfPjuA
Here's an image: 
![unknown](https://user-images.githubusercontent.com/69807322/114899914-ab462400-9e13-11eb-887a-623eb2d6cd83.png)

Have a nice day :)

**Comment by dscalzi** [comment]
```
[AuthManager] Account access token is invalid.
```

Mojang has indicated the access token is invalid. What more could we do?

**Comment by coeragames** [comment]
Effectively.
 But when I try to make this bug on other private launchers, I’m not logged out.

**Comment by drori200** [comment]
Mojang automatically refreshes the session token
Meaning you have to login again

**Comment by coeragames** [comment]
Ah ok.
It's strange
