### ISSUE TITLE
How to add my server the server list? 

### ISSUE THREAD

**Issue by mayerbalint** [dscalzi/HeliosLauncher#161]
Please help all :D

**Comment by DrDeee** [comment]
You have to create your own distribution. You can either use [Nebula](https://github.com/dscalzi/nebula) for this, or you can write them [yourself](https://github.com/dscalzi/HeliosLauncher/blob/master/docs/distro.md).

**Comment by mayerbalint** [comment]
But inside the launcher, how do I add my server? at the start button?

**Comment by DrDeee** [comment]
> But inside the launcher, how do I add my server? at the start button?

You have to fork this project and then you have to replace the url somewhere of the bottom of distromanager.js with the url of your distribution.json

**Comment by mayerbalint** [comment]
![image](https://user-images.githubusercontent.com/82580498/115040512-cd05e080-9ed1-11eb-8630-6c5be56b85a4.png)
Okay and where from here?

**Comment by mayerbalint** [comment]
![image](https://user-images.githubusercontent.com/82580498/115040630-eeff6300-9ed1-11eb-9537-cff346d73821.png)

**Comment by DrDeee** [comment]
> You have to create your own distribution. You can either use [Nebula](https://github.com/dscalzi/nebula) for this, or you can write them [yourself](https://github.com/dscalzi/HeliosLauncher/blob/master/docs/distro.md).

@mayerbalint You need this distribution! This distribution contains your server list and the required files.

**Comment by DrDeee** [comment]
https://github.com/mayerbalint/minecore/blob/fe7b653cc4a1b56491518eb6c25ddd53108e644d/app/assets/js/distromanager.js#L540

This is the line where you have to replace the url with your own.

**Comment by Scrr1pt** [comment]
help

**Comment by mayerbalint** [comment]
can you help set the nebula?
