### ISSUE TITLE
Launch problem with 1.16.5 modpack

### ISSUE THREAD

**Issue by NhProGamer** [dscalzi/HeliosLauncher#165]
After game installation, when the launcher tries to launch the game, it returns this error

[LaunchSuite] Error during launch TypeError: this.constructModArguments is not a function
    at ProcessBuilder.build (C:\Users\neohu\AppDa…rocessbuilder.js:61)
    at ChildProcess.<anonymous> (landing.js:706)
    at ChildProcess.emit (events.js:315)
    at emit (internal/child_process.js:876)
    at processTicksAndRejections (internal/process/task_queues.js:85)

this is the [distrib.json](https://raw.githubusercontent.com/NhSoul/Better-Minecraft/master/distribution.json)

**Comment by NhProGamer** [comment]
problem fixed, it just needed to uncomment

     constructModArguments(mods){
         const argStr = mods.map(mod => {
             return mod.getExtensionlessID()
         }).join(',')

         if(argStr){
             return [
                 '--fml.mavenRoots',
                 path.join('..', '..', 'common', 'modstore'),
                 '--fml.mods',
                 argStr
             ]
         } else {
             return []
         }

     }

line 264 to 279

**Comment by dscalzi** [comment]
That function should not be used. It's suboptimal, what exactly is referencing it in your fork..?
