### ISSUE TITLE
Hello how to change .helioslauncher appdata?

### ISSUE THREAD

**Issue by mayerbalint** [dscalzi/HeliosLauncher#166]
How to change? 
![asónyád](https://user-images.githubusercontent.com/82580498/115967814-00311b00-a535-11eb-8545-1c93b464da2e.PNG)

**Comment by dscalzi** [comment]
https://github.com/dscalzi/HeliosLauncher/blob/48d0c9e5490ad67f58aa88d2920bab9d3af46128/app/assets/js/configmanager.js#L9
