### ISSUE TITLE
SHA256 SUPPORT

### ISSUE THREAD

**Issue by Nobodyno-boop** [dscalzi/HeliosLauncher#169]
Hi, 
I hope its not too much work to change this.
Change md5 to SHAH256.

i understand md5 its more fast, but isn't secure with md5 attack vulnerability

**Comment by juni37** [comment]
Since it is an open-source, how about you just simply fork this repository, and just work it by yourself?

**Comment by Poulpinounette** [comment]
Yep, i after no response i have start the work. 
I will make a PR when i have a stable work

**Comment by jordanamr** [comment]
Gros ça prend 5 minutes t'abuses
