### ISSUE TITLE
Can I create a launcher with mods that install automatically?

### ISSUE THREAD

**Issue by ByMoniXX** [dscalzi/HeliosLauncher#170]
I've searched the internet a lot and I still don't know how to create the launcher with the mod pack, can anyone help me? This would be very helpful

**Comment by gamernitro999** [comment]
you need ti use nebula to create the distribution.json

**Comment by ByMoniXX** [comment]
> you need to use nebula to create the distribution.json


could you pass me the nebula link?

**Comment by ByMoniXX** [comment]
> you need to use nebula to create the distribution.json

You know how to do it?
Could you give me a hand?
Would you help me too much

**Comment by dscalzi** [comment]
Hey, this launcher is something that is intended to be setup by a server/network
1. If you run a modded server and want to make a launcher for your community, helios is a good choice.
2. If you are just a player who wants to launch a specific modpack with helios, this is probably not what you're looking for.

**Comment by ByMoniXX** [comment]
> Oye, este lanzador es algo que está destinado a ser configurado por un servidor / red
> 
> 1. Si ejecuta un servidor modificado y desea crear un lanzador para su comunidad, helios es una buena opción.
> 2. Si solo eres un jugador que quiere lanzar un modpack específico con helios, probablemente esto no sea lo que estás buscando.

I want to create a modpack for a server that I want to open, "a server with mods" but I don't know how to configure the launcher so that my community will download the mods automatically and they can enter my server

Please help, if it's not too much trouble

**Comment by ByMoniXX** [comment]
> Hey, this launcher is something that is intended to be setup by a server/network
> 
> 1. If you run a modded server and want to make a launcher for your community, helios is a good choice.
> 2. If you are just a player who wants to launch a specific modpack with helios, this is probably not what you're looking for.

They clarified that I have a purchased host, this would not be a problem, I like the idea of ​​being able to create a modpack from helios launcher regarding its theme, which is roleplay

**Comment by gamernitro999** [comment]
helios install mods automatically if you have a distribution.json that you can create with nebula
