### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by multyissad** [dscalzi/HeliosLauncher#171]
Please help me!
I generated the json with nebula,
everything works but when i try to load the game this error comes up in the console

[LaunchSuite] Error while downloading: {errno: "ECONNREFUSED", code: "ECONNREFUSED", syscall: "connect", address: "127.0.0.1", port: 8080}

**Comment by Guillaume0001** [comment]
Good evening, there he tells you that he cannot find the files. Surely because you put the address to 127.0.0.1:8080 which is the local address of the website. You have to upload the Nebula files to a website and change its address on the launcher.

**Comment by multyissad** [comment]
> Good evening, there he tells you that he cannot find the files. Surely because you put the address to 127.0.0.1:8080 which is the local address of the website. You have to upload the Nebula files to a website and change its address on the launcher.

understood, where am I supposed to change the address on the launcher tho? i can't find the option ;D

**Comment by multyissad** [comment]
oh i found it ;D thanks
