### ISSUE TITLE
How do I check for updates?

### ISSUE THREAD

**Issue by multyissad** [dscalzi/HeliosLauncher#172]
I changed the string (info.darwindownload) to my server's download path, but it seems like it doesn't download it ? 
Whenever i press on check update it just tells me that im using the latest version... How would i fix it?

**Comment by dscalzi** [comment]
The launcher uses electron-updater (https://www.electron.build/). The configuration on master works. You have to ensure that the urls are updated in places that electron-updater checks. IIRC, this is in package.json but I don't remember 100%.

Recall, the launcher checks Github for new releases. If it's not looking at the correct repository, it will not find any new releases.
