### ISSUE TITLE
Helios Launcher error with stdin

### ISSUE THREAD

**Issue by rudykwerewolf** [dscalzi/HeliosLauncher#182]
Error output:
!include: could not find: "C:\Users\username\launcher\HeliosLauncher-master\node_modules\app-builder-lib\templates\nsis\include\StdUtils.nsh"
Error in script "<stdin>" on line 1 -- aborting creation process

**Comment by Raznardo** [comment]
Do you have any accent in your username ? It doesn't support that

**Comment by dscalzi** [comment]
Reopen if you still have problems
