### ISSUE TITLE
Self signed certificate 

### ISSUE THREAD

**Issue by mrugtangy** [dscalzi/HeliosLauncher#193]
Whenever i'm trying to login, I'm getting the following error :-

![image](https://user-images.githubusercontent.com/74885686/136335560-dc9d2ba2-3cbf-4a60-b0c3-15b477017472.png)

Can someone pls tell me how to fix this?

**Comment by tangyyt912** [comment]
> What is the output on the console ? (use ctrl+shift+i) go to console and screen the error

C:\Users\shiva\Downloads\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\app\assets\js\loggerutil.js:25 [Mojang] Error during authentication. Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497)
    at TLSSocket.emit (events.js:315)
    at TLSSocket._finishInit (_tls_wrap.js:932)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706)
error @ C:\Users\shiva\Downloads\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\app\assets\js\loggerutil.js:25
(anonymous) @ C:\Users\shiva\Downloads\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\app\assets\js\mojang.js:154
self.callback @ C:\Users\shiva\Downloads\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\node_modules\request\request.js:185
emit @ events.js:315
Request.onRequestError @ C:\Users\shiva\Downloads\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\node_modules\request\request.js:877
emit @ events.js:315
socketErrorListener @ _http_client.js:469
emit @ events.js:315
emitErrorNT @ internal/streams/destroy.js:106
emitErrorCloseNT @ internal/streams/destroy.js:74
processTicksAndRejections @ internal/process/task_queues.js:80
C:\Users\shiva\Downloads\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\HeliosLauncher-f9e4fd85617678fd8991324322b6f9347f4e2462\app\assets\js\loggerutil.js:9 [Login] Error while logging in. Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497)
    at TLSSocket.emit (events.js:315)
    at TLSSocket._finishInit (_tls_wrap.js:932)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706)

**Comment by tangyyt912** [comment]
> Are you trying to run the launcher behind a proxy?

nope

**Comment by gamernitro999** [comment]
@dscalzi you can close this issue he said on discord that he use an alternative auth system so the error don't come from helios

@tangymc if you know that it fails on auth when you use a custom auth system don't open an issue on helios but on the auth system that you're using
