### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by darthNihilu** [dscalzi/HeliosLauncher#195]
Hi, I've got some troubles to start using it. I installed the latest version from release notes, and when I run the Launcher, I've got error message in console: **[Preloader]** _Error: certificate has expired_
![image](https://user-images.githubusercontent.com/31260382/137647455-26e4f29d-edd4-42c4-83b3-08152a9ecd79.png)

**Comment by extremepro999** [comment]
> Important Note: this works only when installing launcher from release notes. When i started dev and builded dist - everything works for me

I have this issue too, did you find a fix?

**Comment by drori200** [comment]
Implement commit f9e4fd85617678fd8991324322b6f9347f4e2462 using git cherry-pick f9e4fd85617678fd8991324322b6f9347f4e2462 or just copy the changes

**Comment by dscalzi** [comment]
Please stay up to date with master at all times.
