### ISSUE TITLE
Add Support for Java 9 (10, 11)+ discovery in preparation for Forge 1.13

### ISSUE THREAD

**Issue by dscalzi** [dscalzi/HeliosLauncher#20]
Forge 1.13 will support Java 9+, therefore we also need to support installations of these versions for 1.13+. Java 8 will remain our primary candidate for discovery and installation (at least until oracle starts hiding downloads behind a login). 

#### All OS

Ensure the output of `java -XshowSettings:properties` has not changed. If it has, update accordingly.

#### Windows

The registry keys for Java 9+ have changed, we will need to add support for them.

#### MacOS + Linux

Tests need to be run to make sure installation directories and fs structure have not changed.

---

https://docs.oracle.com/javase/10/install/overview-jdk-10-and-jre-10-installation.htm#JSJIG-GUID-8677A77F-231A-40F7-98B9-1FD0B48C346A

---

No ETA on this. WesterosCraft is unlikely to update to 1.13 for at least another year, however the launcher should be made compatible as soon as possible. I would like to begin working on this by the time Forge 1.13 is available.

**Comment by dscalzi** [comment]
Preliminary support added. Java 9 + 10 are EOL and Oracle's JDK 11 is not free to use in production. This means we would need to use OpenJDK for 11+, which afaik does not have an installer. No installer = no registry keys = we don't need to bother with that on windows. As this gets closer to being relevant I'll run some more in depth tests to see what we need to support.

Java 9+ is still disabled for all versions until we test mod compatibility on a far-future 1.13 test server.

Changes untested on macOS and Linux.

**Comment by lpuv** [comment]
Is there any progress on this @dscalzi?
Thanks

**Comment by dscalzi** [comment]
It is supported as described below:
MC 1.7-1.16 = JDK 8
MC 1.17+ = JDK 17

via https://github.com/dscalzi/HeliosLauncher/pull/261

going to close this.
