### ISSUE TITLE
adding microsoft login option

### ISSUE THREAD

**Issue by roxarr** [dscalzi/HeliosLauncher#201]
good morning. can anyone help me to add a microsoft login option? because when I tried to implement it myself, after entering the npm start command, it crashes on the loading screen, and keeps loading and loading and nothing.

**Comment by Neerfix** [comment]
https://github.com/dscalzi/HeliosLauncher/issues/131

**Comment by gbeag** [comment]
#186

**Comment by dscalzi** [comment]
Closing in favor of #210
