### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by Banane480** [dscalzi/HeliosLauncher#203]
Alors j'ai mis ma cle de client la ou il faut et quand je lance le launcher après m'être connecte il dit : Error 401.
Je ne sais pas d'où vient ce problème puis-je avoir de l'aide ?

**Comment by gamernitro999** [comment]
send a screenshot

**Comment by GeekCornerGH** [comment]
For now, we don't support Microsoft accounts

**Comment by dscalzi** [comment]
3rd party solutions for Microsoft authentication is not supported. Official support is nearing completion.

Closing in favor of #210
