### ISSUE TITLE
Add fixes for Log4j expliot 

### ISSUE THREAD

**Issue by NordicGamerFE** [dscalzi/HeliosLauncher#206]
Creeperhost has released a fix that MIT that could be integrated probably
https://github.com/CreeperHost/Log4jPatcher/tree/v1.0.1

**Comment by dscalzi** [comment]
Information has also been posted in #announcements on our discord.

**Comment by gamernitro999** [comment]
i don't understand why creeperhost have made a patch you juste need to update the library

**Comment by dscalzi** [comment]
See #announcements, follow the guidance for your client provider. Helios will download whatever updates you apply.

**Comment by NordicGamerFE** [comment]
Because forge and mods

**Comment by GeekCornerGH** [comment]
Helios will apply all updates from Mojang's server. For yourself, you will have to update Forge
