### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by SaGye9816** [dscalzi/HeliosLauncher#207]
![12](https://user-images.githubusercontent.com/91346207/145725725-214ab03e-6434-47c6-91d3-0869b9538cc6.png)

download error....

**Comment by Banane480** [comment]
Moi aussi j'ai le même problème et je ne sais pas comment le regler

**Comment by gamernitro999** [comment]
do you have a ssl cert on your web server ?
if yes idk
if no change the url to a http one

**Comment by Banane480** [comment]
mais mon server web est en https

**Comment by TheoPierne** [comment]
I think it can be a lot of causes:
- Rate limit on your server.
- Firewall on your server. (Not sure)
- Too many requests on your server so it can't keep up. (This cause the request to timeout)

Maybe others causes are involved, but I don't see which ones

**Comment by dscalzi** [comment]
The connection to your server timed out. Ensure it is online and reachable.
