### ISSUE TITLE
fatal error: unable to Load distribution Index Helios Launcher

### ISSUE THREAD

**Issue by ItzzParsher** [dscalzi/HeliosLauncher#209]
![image](https://user-images.githubusercontent.com/96580067/147244489-e795ac6b-ed64-4449-9762-04660dfae427.png)
How to fix this?

**Comment by gamernitro999** [comment]
first ctrl + shift + i and show the console

**Comment by ItzzParsher** [comment]
> first ctrl + shift + i and show the console

![image](https://user-images.githubusercontent.com/96580067/147245202-e5a23f20-b724-4ff2-8e17-c809ad5cec66.png)
here :L

**Comment by ItzzParsher** [comment]
> first ctrl + shift + i and show the console

here is a file .txt :l 
[-1640269866972.log](https://github.com/dscalzi/HeliosLauncher/files/7769849/-1640269866972.log)
