### ISSUE TITLE
Microsoft authorization

### ISSUE THREAD

**Issue by MJRamon** [dscalzi/HeliosLauncher#210]
Can you please add new Microsoft authorization? Players are migrating now.

**Comment by gbeag** [comment]
#186

**Comment by roccscout** [comment]
Is there any update on this?

**Comment by gamernitro999** [comment]
#143 by the community that all

**Comment by dscalzi** [comment]
@GeekCornerGH informed me of https://www.minecraft.net/en-us/article/last-call-voluntarily-migrate-java-accounts, so this is probably going to have elevated urgency.

**Comment by dscalzi** [comment]
WIP Microsoft Auth implementation: https://github.com/dscalzi/HeliosLauncher/compare/feature/ms-auth
There are a few more things that need to be done. Feel free to checkout and take a look. This code is not production-ready until it is merged to master.
