### ISSUE TITLE
AutoConnect 

### ISSUE THREAD

**Issue by Banane480** [dscalzi/HeliosLauncher#211]
J'ai active l'option auto connect sur mon launcher mais quand minecraft ce lance ca m'auto connect pas. Comment je fais ?

**Comment by dscalzi** [comment]
What version

**Comment by Banane480** [comment]
1.12.2 - 14.23.5.2860

**Comment by TheoPierne** [comment]
Pour que l'auto connect fonctionne, il faut que tu l'actives dans le launcher mais aussi dans ton fichier de distribution (`distribution.json`) que tu as généré auparavant.

```json
"mainServer": false,
"autoconnect": true, <-
"modules": [...]
```

**Comment by Banane480** [comment]
Okay merci !
