### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by kmsimproject** [dscalzi/HeliosLauncher#214]
![image](https://user-images.githubusercontent.com/68764872/151492152-960cfcc2-937a-4e5f-babe-62a7bba34e8d.png)

how to fix?

**Comment by luuxis** [comment]
try to update electron
```console
npm i electron@16
```

**Comment by kmsimproject** [comment]
![image](https://user-images.githubusercontent.com/68764872/151495551-3657e5a4-3cb4-4376-afe7-1ee99486527e.png)
If you change the electron version, another error appears and does not run.

**Comment by luuxis** [comment]
joining the discord server will be much easier to help you https://discord.gg/hkNkrkArRx

**Comment by kmsimproject** [comment]
okay
