### ISSUE TITLE
"expiresAt" does not get populated, leading to invalid sessions errors.

### ISSUE THREAD

**Issue by eDexiam** [dscalzi/HeliosLauncher#217]
Hi, after doing some testing and checks I've noticed that the "expiresAt" field in the config does not get populated.
The check that verifies if the account is expired always returns false meaning that the launcher will never attempt refreshing any of tokens be it MC or MS.

![image](https://user-images.githubusercontent.com/29255472/154064881-0d38956b-6a8e-44a0-8af6-ddf59847f289.png)

I've been able to pin point what the issue is in `authmanager.js`, the `calculateExpiryDate` method is async, however it is not awaited anywhere where it is used so the returned data is a promise instead of the expected number value. Simply awaiting the method from what I can tell should resolve the problem.

**Comment by eDexiam** [comment]
I forgot to mention this is an issue on the new 1.9.0 version that has just been released a few days ago.

**Comment by dscalzi** [comment]
I'll check

**Comment by dscalzi** [comment]
Good catch, thanks. Fixed with https://github.com/dscalzi/HeliosLauncher/commit/b0927224885e4307ac787fe779d64d60b0c8bc7c
