### ISSUE TITLE
linux can't build 

### ISSUE THREAD

**Issue by Banane480** [dscalzi/HeliosLauncher#223]
aidan@raspberrypi:~/Desktop/erangel/launcher/erangellauncher $ npm run dist:linux

> erangellauncher@3.0.2 dist:linux /home/aidan/Desktop/erangel/launcher/erangellauncher
> npm run dist -- -l

> erangellauncher@3.0.2 dist /home/aidan/Desktop/erangel/launcher/erangellauncher
> electron-builder build "-l"

Error: Cannot find module 'fs/promises'
Require stack:
- /home/aidan/Desktop/erangel/launcher/erangellauncher/node_modules/builder-util/out/fs.js
- /home/aidan/Desktop/erangel/launcher/erangellauncher/node_modules/builder-util/out/util.js
- /home/aidan/Desktop/erangel/launcher/erangellauncher/node_modules/electron-builder/out/cli/cli.js
- /home/aidan/Desktop/erangel/launcher/erangellauncher/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/aidan/Desktop/erangel/launcher/erangellauncher/node_modules/builder-util/src/fs.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/aidan/Desktop/erangel/launcher/erangellauncher/node_modules/builder-util/src/util.ts:25:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! erangellauncher@3.0.2 dist: `electron-builder build "-l"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the erangellauncher@3.0.2 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aidan/.npm/_logs/2022-05-07T08_30_11_131Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! erangellauncher@3.0.2 dist:linux: `npm run dist -- -l`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the erangellauncher@3.0.2 dist:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aidan/.npm/_logs/2022-05-07T08_30_13_982Z-debug.log

How to fix ?? I'm bad wih linux...

**Comment by gamernitro999** [comment]
i'm really not sure but maybe you can't compile helios (i'm really not sure) on arm (raspberrypi are arm-based) so try on a virtual machine if you don't have non arm linux computer

**Comment by Banane480** [comment]
Okay let me a moment XD

**Comment by Banane480** [comment]
Let me a few days pls XD

**Comment by GeekCornerGH** [comment]
please upgrade your nodejs to v16

**Comment by Banane480** [comment]
What is GitHub action and ok for node 16

**Comment by GeekCornerGH** [comment]
Please take a look on [here](https://github.com/features/actions)

**Comment by Banane480** [comment]
So I will try this week end on Linux (sorry for delay). I have an another question, can we set a gif in background ??

**Comment by gamernitro999** [comment]
to set certificate first you need to buy one (it's expensive) and next sign the launcher it's an electron app search on internet to know what to do, for the gif i don't know but you can try yourself and see

**Comment by Banane480** [comment]
thanks ! (now I have an another problem and again sorry for the delay) 



**PS C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher> npm start

> erangellauncher@3.0.3 start
> electron .

'electron' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
PS C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher> npm i    
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN tarball tarball data for minimatch@https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz (sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==) seems to be corrupted. Trying again.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN tarball tarball data for minimatch@https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz (sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA== integrity checksum failed when using sha512: wanted sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA== but got sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==. (11423 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aidan\AppData\Local\npm-cache\_logs\2022-05-12T15_01_18_706Z-debug-0.log
PS C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher>**

**Comment by gamernitro999** [comment]
it's another problem so it's off topic (so open a new issue) but anyways are you sure that your nodejs is updated ?

**Comment by Banane480** [comment]
I have node 16 and I already have repair it (I'll crête new issue tomorrow and I try Linux tomorrow too

**Comment by Banane480** [comment]
with node 16 


┌──(aidan㉿KaliDeAidan)-[~/Bureau/launcher/erangellauncher]
└─$ npm i
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN tarball tarball data for minimatch@https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz (sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==) seems to be corrupted. Trying again.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN tarball tarball data for minimatch@https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz (sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA== integrity checksum failed when using sha512: wanted sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA== but got sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==. (11423 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aidan/.npm/_logs/2022-05-14T08_01_18_469Z-debug-0.log

**Comment by gamernitro999** [comment]
apparently minimatch is corrupted for you

**Comment by gamernitro999** [comment]
are you sure that your npm in updated to the latest version ?

**Comment by Banane480** [comment]
No, not the latest

**Comment by Banane480** [comment]
And how to fix "mini match"

**Comment by Banane480** [comment]
okay so it worked. I have the .AppImage but I can't launch it...

**Comment by GeekCornerGH** [comment]
A quick [search on Google](https://www.google.com/search?q=how+to+launch+appimage&oq=how+to+launch+appimage) shows intresting things

**Comment by Banane480** [comment]
Thanks boy! Juste a question, can we set gif en backround ?? (I'm bad in development)

**Comment by gamernitro999** [comment]
> Thanks boy! Juste a question, can we set gif en backround ?? (I'm bad in development)

i don't know but just take a gif and try it yourself

**Comment by Banane480** [comment]
Okay I close the bug
