### ISSUE TITLE
Failed to login : Invalid session

### ISSUE THREAD

**Issue by Banane480** [dscalzi/HeliosLauncher#224]
Hum I don't know if that's ans Helios error but when I want to connect on my server, it often tells me "Failed to Login : Invalid session. To fix that's we need to disconnect our Microsoft account from the launcher and re-connect it. It's boring.

Does anyone known how to fix ??

(Sorry for my bad English : I'm not English

**Comment by gamernitro999** [comment]
there is no way to fix it the problem isn't from helios it come from the login system of minecraft sorry

**Comment by Banane480** [comment]
Okay

**Comment by TheoPierne** [comment]
Related to: #226 
So it has been patched by the merge !
