### ISSUE TITLE
The problem of auto update

### ISSUE THREAD

**Issue by karu724** [dscalzi/HeliosLauncher#230]
When an updated version of the launcher exists, the launcher is cleared by turning off the launcher after the download is complete, turning off the system, and then turning it back on.

**Comment by TheoPierne** [comment]
Don't know if I fully understand the problem, but your launcher only updates if you totally reboot your computer ?

**Comment by karu724** [comment]
I misspoke. I mean, if the launcher turns off the OS during an update in the background, the launcher is broken.

**Comment by dscalzi** [comment]
Would need more details
