### ISSUE TITLE
Cannot be updated

### ISSUE THREAD

**Issue by ClubOfGames** [dscalzi/HeliosLauncher#231]
Hello,

I tried in the code to modify the link of the github by mine, but when the launcher is online with a new update on github, the launcher does not detect it. Could I have some help please?

I changed the link at line 53 in uicore.js

**Comment by TheoPierne** [comment]
Hello,

If you're using the launcher in the development environment it won't update, you have to install it (after a full build) like a normal player to check if the auto update work. (https://github.com/dscalzi/HeliosLauncher/blob/master/app/assets/js/scripts/uicore.js#L42)

_P.S.: The line 53 in uicore.js just work if your launcher is used on Mac OS_

**Comment by christophe-merlen** [comment]
Hello,

For the launcher to detect that there is a new update, you must add the latest.yml in your releases.

If this answered your questions, do not hesitate to close the issue. This will help the creator by decreasing the amount of issues to be answered.

**Comment by dscalzi** [comment]
Assuming you've updated your package.json to point to your github url:

1. Setup GitHub actions as it's configured in this repository.
2. Create a draft release. Set the tag to `v${version_defined_in_package.json}`. Ie `v2.0.0`
3. Push your changes, make sure the version matches the tag. Electron-builder will upload the executables to the draft release.
4. Wait for GitHub actions to finish
5. Publish the draft release.
