### ISSUE TITLE
Can't use forge 1.16.6 ? 

### ISSUE THREAD

**Issue by Banane480** [dscalzi/HeliosLauncher#235]
How can we use forge 1.16.5 on helios ? (universal format doesn't exist)

**Comment by TheoPierne** [comment]
You can use any version until [Nebula](https://github.com/dscalzi/Nebula) support it. When you want to generate a new server, you can specify a version of forge to use `npm run start -- generate server <id> <version> <options>` -> `npm run start -- generate server Test1 1.16.5 --forge 36.2.35`

**Comment by Banane480** [comment]
Yes but we don't need to fill "librairies" with forge 1.16.5 universal ?

**Comment by gamernitro999** [comment]
no nebula take care of anything

**Comment by Banane480** [comment]
So what I need to put in this folder ?

**Comment by gamernitro999** [comment]
go on the discord and do /nebula in the helios-general channel
