### ISSUE TITLE
Add news to news section

### ISSUE THREAD

**Issue by itsGabyMC** [dscalzi/HeliosLauncher#243]
Hello, how can I add an iframe of a web page with the news about the launcher in the news section? I'm starting to study programming and I don't know much about it, please help me. Thanks.

**Comment by Mimexe** [comment]
you need an rss feed

**Comment by dscalzi** [comment]
I would not use an iframe, it looks awkward. Use an RSS feed to send news data to the launcher and build UI elements around the data. Helios has this built in already, xenforo and other software should have rss feeds.
