### ISSUE TITLE
License not compatible with helios-core

### ISSUE THREAD

**Issue by blarfoon** [dscalzi/HeliosLauncher#247]
I just noticed this repo is marked as MIT but a dependency (helios-core) is LGPL. These 2 licenses are completely incompatible hence making this codebase effectively proprietary. Can this be solved?

**Comment by dscalzi** [comment]
LGPL is not a proprietary license and it is perfectly fine to have an MIT licensed product use a LGPL library. Not sure what the hangup here is?

**Comment by killpowa** [comment]
You can't use an LGPL license under a more permissive license (MIT) because that means that you are allowing people to use the LGPL library included in this repo in proprietary code as well (allowed by MIT but not by LGPL). This is why they are incompatible.

**Comment by killpowa** [comment]
Oh you're right, I missed the (L) part of the license, my bad. Thanks for clarifying it

**Comment by dscalzi** [comment]
No problem, easy to miss haha
