### ISSUE TITLE
Error: Cannot not find module '@electron/remote/main'

### ISSUE THREAD

**Issue by kmsimproject** [dscalzi/HeliosLauncher#248]
![image](https://user-images.githubusercontent.com/68764872/189100186-1d392890-527b-482f-880c-eb28dacd86e3.png)

I copied the code in sample_distribution.json as it is, created a link using the github raw, and put the link in the distromanger, and this error appears. How do I fix this?

**Comment by GeekCornerGH** [comment]
May you show me your package.json please?

**Comment by dscalzi** [comment]
Did you run npm install..?

**Comment by kmsimproject** [comment]
> Did you run npm install..?

yes

**Comment by kmsimproject** [comment]
> May you show me your package.json please?
`{
  "name": "helioslauncher",
  "version": "1.9.0",
  "productName": "Helios Launcher",
  "description": "Modded Minecraft Launcher",
  "author": "Daniel Scalzi (https://github.com/dscalzi/)",
  "license": "UNLICENSED",
  "homepage": "https://github.com/dscalzi/HeliosLauncher",
  "bugs": {
    "url": "https://github.com/dscalzi/HeliosLauncher/issues"
  },
  "private": true,
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "dist": "electron-builder build",
    "dist:win": "npm run dist -- -w",
    "dist:mac": "npm run dist -- -m",
    "dist:linux": "npm run dist -- -l",
    "lint": "eslint --config .eslintrc.json ."
  },
  "engines": {
    "node": "16.x.x"
  },
  "dependencies": {
    "@electron/remote": "^0.0.1",
    "adm-zip": "^0.5.9",
    "async": "^3.2.3",
    "discord-rpc-patch": "^4.0.1",
    "ejs": "^3.1.6",
    "ejs-electron": "^2.1.1",
    "electron-updater": "^4.6.5",
    "fs-extra": "^10.0.0",
    "github-syntax-dark": "^0.5.0",
    "got": "^11.8.3",
    "helios-core": "~0.1.0",
    "jquery": "^3.6.0",
    "node-stream-zip": "^1.15.0",
    "request": "^2.88.2",
    "semver": "^7.3.5",
    "tar-fs": "^2.1.1",
    "winreg": "^1.2.4"
  },
  "devDependencies": {
    "electron": "^20.1.2",
    "electron-builder": "^23.5.0",
    "eslint": "^8.8.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/dscalzi/HeliosLauncher.git"
  }
}
`
here

**Comment by kmsimproject** [comment]
+ i'm installed @electron/remote

**Comment by VonDefiant** [comment]
did you solve it? I have the same error

**Comment by gamernitro999** [comment]
1. make sure that you have the right nodejs version : minimum node 16
2. run `npm i`

**Comment by VonDefiant** [comment]
if I have a version and also execute the command and I get the same error

**Comment by VonDefiant** [comment]
![image](https://user-images.githubusercontent.com/91977851/190862517-f6543269-8a7b-43f2-a392-62f3f0164a28.png)

I get this after putting the command

**Comment by drori200** [comment]
> ![image](https://user-images.githubusercontent.com/91977851/190862517-f6543269-8a7b-43f2-a392-62f3f0164a28.png)
> 
> I get this after putting the command

Not an error just a warning

**Comment by VonDefiant** [comment]
running npm start gives me the error :c

![image](https://user-images.githubusercontent.com/91977851/190863166-70383ed2-3a53-4795-be2c-cb50b72df25a.png)

**Comment by gamernitro999** [comment]
do `node --version` please

**Comment by VonDefiant** [comment]
there is 

![image](https://user-images.githubusercontent.com/91977851/190863605-8c5b5698-1c51-4c21-af64-f7b0d41485df.png)

**Comment by gamernitro999** [comment]
Oh ... use another folder, reason : fuck onedrive

**Comment by VonDefiant** [comment]
![image](https://user-images.githubusercontent.com/91977851/190863935-c4f07690-f6eb-40d5-a6e6-93996bcb9be1.png)

I already changed folder and I get the same

**Comment by gamernitro999** [comment]
have you modified or did anything before npm i and npm start ?

**Comment by VonDefiant** [comment]
just change the name of the launcher and put my git profile

**Comment by gamernitro999** [comment]
ok so should not cause problems

**Comment by gamernitro999** [comment]
I think it come from your environement so maybe try in a fresh vm

**Comment by VonDefiant** [comment]
ok thanks i will try

**Comment by VonDefiant** [comment]
I already left thank you very much
![image](https://user-images.githubusercontent.com/91977851/190864922-e059f2f8-162e-455f-9b27-efe82cb95373.png)

**Comment by kmsimproject** [comment]
> npm i와 npm이 시작되기 전에 수정했거나 아무 것도하지 않았습니까?

i'm was deleted package lock json

**Comment by kmsimproject** [comment]
> I think it come from your environement so maybe try in a fresh vm

how to fix?

**Comment by dscalzi** [comment]
@VonDefiant could you explain what caused your issue and how to fix it, for anyone else having this? I have never had this issue so I can't really comment.

**Comment by VonDefiant** [comment]
@dscalzi 
reinstall the node JS and select the option that marks in the image after that I tried to execute the command again and it worked
![image](https://user-images.githubusercontent.com/91977851/190929530-e515f9f4-f39e-4dea-88f5-c400e3cbf3ea.png)

**Comment by VonDefiant** [comment]
You should install only npm package manager and check the box to install all tools, that worked for me
