### ISSUE TITLE
Error: [Minecraft] Unrecognized VM option 'UseConcMarkSweepGC'

### ISSUE THREAD

**Issue by Mimexe** [dscalzi/HeliosLauncher#249]
I'm using Java 17 for MC 1.18.2 
Branch for 1.17

![image](https://user-images.githubusercontent.com/74558118/192118633-20b87764-e480-45ef-a843-da30acf4dceb.png)

**Comment by dscalzi** [comment]
remove the jvm arguments

**Comment by Mimexe** [comment]
how

**Comment by Mimexe** [comment]
Okay, i think i do it but i have this `java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [C:\Users\minim\AppData\Roaming\.XXXXXX\common\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.1.80\lowcodelanguage-1.18.2-40.1.80.jar]`
