### ISSUE TITLE
Could not start minecraft 

### ISSUE THREAD

**Issue by karu724** [dscalzi/HeliosLauncher#251]
![image](https://user-images.githubusercontent.com/89616569/193400379-3b312603-29e0-467c-a4a2-51540d84f1e1.png)

[Minecraft] Exception in thread "main" 
E:\코딩\minecraft\Ria-Network\app\assets\js\loggerutil.js:9 [Minecraft] java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
    at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

E:\cc\minecraft\Ria-Network\app\assets\js\loggerutil.js:9 [ProcessBuilder] Exited with code 1

**Comment by dscalzi** [comment]
This is a java compatibility issue, you need to run 1.12 and below on java 8.
