### ISSUE TITLE
change basic login to crack login 

### ISSUE THREAD

**Issue by royaljacques** [dscalzi/HeliosLauncher#258]
hello
having discovered your launcher written with electron , I wanted to know how I could modify the login of the launcher to make it a login crack . thank you in advance

**Comment by splatboydev** [comment]
No support is provided with making cracked login.

As taken from the discord:
Helios Launcher doesn't supports cracked (or offline) version of Minecraft. And he never will.
**Cracked versions of Minecraft are illegal.**
When playing Minecraft, you agree the [Mojang's Terms](https://account.mojang.com/terms), that say you need to own a copy of the game to play Minecraft.
We won't help you about cracked versions.

**Comment by royaljacques** [comment]
I have minecraft, and just want to be able to bring a double account on my server to be able to film. not having the means to buy me another account

**Comment by LucasB25** [comment]
It’s not as much ilagale since Mojande for years totally approves of the crack account and their main source of players comes from the cracks

**Comment by gamernitro999** [comment]
> I have minecraft, and just want to be able to bring a double account on my server to be able to film. not having the means to buy me another account

it's still illegal as it's not authorized by Mojang's terms nor that it is by microsoft and law from almost all countries make piracy illegal so we don't care about why you want it **cracked version are illegal because of the law of almost every countries and we won't help you at all on this**

> It’s not as much ilagale since Mojande for years totally approves of the crack account and their main source of players comes from the cracks

1. law make it illegal
2. what someone say don't change the terms
3. microsoft bought mojang and microsoft don't support cracked versions and piracy at all
4. > main source of players comes from the cracks

ok cool for them. it's still illegal

**Comment by gamernitro999** [comment]
now I suggest you to close this issue as you have your answer and nothing will change it

**Comment by GeekCornerGH** [comment]
> It’s not as much ilagale since Mojande for years totally approves of the crack account and their main source of players comes from the cracks

Yes, Notch said it was okay to use cracks, but Notch left Mojang since many years.
Regarding offline mode from servers options, this mode is designed if mojang servers are down  (or the server does not have internet connection).

Helios Launcher doesn't supports cracks, period.

**Comment by LucasB25** [comment]
> > It’s not as much ilagale since Mojande for years totally approves of the crack account and their main source of players comes from the cracks
> 
> Yes, Notch said it was okay to use cracks, but Notch left Mojang since many years. Regarding offline mode from servers options, this mode is designed if mojang servers are down (or the server does not have internet connection).
> 
> Helios Launcher doesn't supports cracks, period.
I know very well, but from what I saw you created a version accepting cracks

**Comment by gamernitro999** [comment]
if someone make something illegal it doesn't mean that you should follow him

**Comment by LucasB25** [comment]
> if someone make something illegal it doesn't mean that you should follow him

Anyway without the cracks there would be 60% less players so whatever it is it suits them well

**Comment by gamernitro999** [comment]
we don't care about that myabe crack made a part of the community but it's still illegal and helios don't support anything that is illegal so please stop answering there is no debate, **We don't support cracked version or help people to support it and it won't change.**

**Comment by dscalzi** [comment]
Helios Launcher does not support cracked officially.
