### ISSUE TITLE
ECONNRESET Error on Minecraft assets domain

### ISSUE THREAD

**Issue by ghost** [dscalzi/HeliosLauncher#268]
Hello,

There is a small problem when I download Minecraft assets in 1.19.3 (not tested previous versions).

There is an ECONNRESET that occurs (I'm not the only one, it does it to some friends too). I've noticed that this error occurs on sounds most of the time.
([https://resources.download.minecraft.net/aa/aa1d3aace1c481ac32d5827fba287294b6bc99fb](https://resources.download.minecraft.net/aa/aa1d3aace1c481ac32d5827fba287294b6bc99fb)
[https://resources.download.minecraft.net/b8/b83bbafa9799680da24f10215de2c40b73ce1fe3](https://resources.download.minecraft.net/b8/b83bbafa9799680da24f10215de2c40b73ce1fe3))

After reloading the application, this problem disappears for the first sound download (ECONNRESET error), and appears for the second sound download (ECONNRESET error). 
Reloading the application again makes the problem disappear.

Is there a solution or an explanation for this problem?

Thanks.

**Comment by dscalzi** [comment]
rewriting assetguard, let's see if that fixes anything..

https://github.com/dscalzi/HeliosLauncher/pull/270

**Comment by dscalzi** [comment]
@DamsDev1 #270 is testable if you want to give it a whirl
