### ISSUE TITLE
How to publish a new release?

### ISSUE THREAD

**Issue by Chicodouille** [dscalzi/HeliosLauncher#269]
Hello, can you help me? I want to publish a new release of my launcher but idk how to do that :/ Thank for you respond :)

**Comment by christophe-merlen** [comment]
Hello if you mean create a build of the application, you can simply open a new terminal in your editor, and type the following command:
For windows: npm run dist -- -w
For linux: npm run dist -- -l
For MacOS: npm run dist -- -m

But if you mean create a new realease on github, you can search on youtube, I'm sure you'll find what you're looking for.

**Comment by dscalzi** [comment]
Assuming you've updated your package.json to point to your github url:

1. Setup GitHub actions as it's configured in this repository.
2. Create a draft release. Set the tag to `v${version_defined_in_package.json}`. Ie `v2.0.0`
3. Push your changes, make sure the version matches the tag. Electron-builder will upload the executables to the draft release.
4. Wait for GitHub actions to finish
5. Publish the draft release.
