### ISSUE TITLE
Name in installer

### ISSUE THREAD

**Issue by ghost** [dscalzi/HeliosLauncher#278]
I changed the name of the Launcher and now I call it Hardium and I would like to know how we can change the name in the installer?

Here is my github: https://github.com/MrPiano5454/HardiumLauncher

**Comment by GeekCornerGH** [comment]
Edit electron-builder.yml

**Comment by MrPiano5454** [comment]
Thanks,

I managed to change the name of the installer, but when I look in the Launcher settings I still see that the files are in the .helioslauncher folder
Can I change? If so which file?

**Comment by GeekCornerGH** [comment]
Feel free to ask on Discord, link is on the Readme file.

I would ask @dscalzi to close this issue, as GitHub issues are used to track issues/future plans regarding launcher, not really much questions.
