### ISSUE TITLE
Move all strings to language file.

### ISSUE THREAD

**Issue by dscalzi** [dscalzi/HeliosLauncher#28]
Put all strings into a language file. Not sure if we need to do this for console messages.

Language file should be json with the following format:

```json
{
    "ui": {
        "landing": {
            "myProperty": "String"
        }
    }
}
```

etc.

Language file should also contain urls and all other hardcoded strings which can be changed per server. Considering having a default file so that shared values (name, urls, etc) do not have to be repeated. They would be declared in a parent file and not declared in the child. If they are declared in the child, the parent's values are overriden.

**Comment by Harjot1Singh** [comment]
I'll try to carve out some time to have a crack at this.

**Comment by Superkooka** [comment]
Why not, in json, create two children in html, text and link? 
```javascript
// Load language
for(let key of Object.keys(Lang.query('html'))){
    if(document.getElementById(key).href)
        document.getElementById(key).href = Lang.query(`html.link.${key}`)
    if(document.getElementById(key).innerText)
         document.getElementById(key).innerHTML = Lang.query(`html.text.${key}`)
}`

**Comment by Superkooka** [comment]
Can I create two child for `html` ?
```javascript
// Load language
for(let key of Object.keys(Lang.query('html'))){
    if(document.getElementById(key).href)
        document.getElementById(key).href = Lang.query(`html.link.${key}`)
    if(document.getElementById(key).innerText)
        document.getElementById(key).innerHTML = Lang.query(`html.text.${key}`)
}`

**Comment by dscalzi** [comment]
No longer persuing this for v1.
