### ISSUE TITLE
Creating a launcher installer .exe

### ISSUE THREAD

**Issue by ghost** [dscalzi/HeliosLauncher#280]
I was wondering how to make a file like this in the release. https://github.com/dscalzi/HeliosLauncher/releases/download/v1.10.0/Helios-Launcher-setup-1.10.0.exe

**Comment by dscalzi** [comment]
It's on the readme

![image](https://user-images.githubusercontent.com/9703873/227634634-88308791-0692-428d-816b-ceb886b25d6e.png)

The executables on the releases are built by github actions https://github.com/dscalzi/HeliosLauncher/blob/master/.github/workflows/build.yml

**Comment by Louxa16** [comment]
yes I apologie for this. Sorry.
