### ISSUE TITLE
Client ID

### ISSUE THREAD

**Issue by ItsRes** [dscalzi/HeliosLauncher#288]
what do i put as the Client ID in the distribution file,

**Comment by GeekCornerGH** [comment]
The clientid field is meant for the Discord RPC. You must read some docs regarding RPC. Also, for questions, please use [Discord](https://discord.gg/zNWUXdt)

**Comment by dscalzi** [comment]
You can remove the discord object if you don't want to set up RPC

**Comment by ItsRes** [comment]
i got it to work i removed the RPC from the distribution file and deleted the discordwrapper.js and imported discord-rpc so i can run the set activity
