### ISSUE TITLE
Legal clarification needed in README

### ISSUE THREAD

**Issue by ItsQuadrus** [dscalzi/HeliosLauncher#292]
**The problem**
The project's README file includes a section titled "Note on Third-Party Usage" that requests users to provide credit to the original author and a link to the original source.

>### Note on Third-Party Usage
>
>Please give credit to the original author and provide a link to the original source. This is free software, please do at least this much.

While the MIT License grants users the freedom to use the software without the obligation to provide attribution, this section in the README might lead to confusion regarding the project's licensing requirements. It would be helpful to clarify this discrepancy to avoid any misunderstandings among users.

**Proposed solution**
I suggest updating the README file to align with the MIT License terms. This could involve removing or modifying the section to clearly indicate that attribution is not mandatory under the MIT License. This will help ensure consistency and avoid potential confusion.

**Additional context**
I fully support open source projects and attribution, but this note in the README would be misleading for new users.

**Comment by gamernitro999** [comment]
this part of the README means that it's not required but we just ask to do it if the the person wants, the usage of the word "please", maybe changing it to make it more obvious can have advantages but I personally don't think a change is needed

**Comment by ItsQuadrus** [comment]
> the usage of the word "please"

Yes, I agree with that, but only for the second sentence.

For the first sentence, "please" implies "You must". I think it needs to be switched up to "You may"

**Comment by ItsQuadrus** [comment]
Opened #294

**Comment by dscalzi** [comment]
The note literally says this is free software. I don't see how it's misleading.

**Comment by ItsQuadrus** [comment]
Clarified the misunderstanding in #295.
