### ISSUE TITLE
rss: Launcher freezing with 2 tags

### ISSUE THREAD

**Issue by GeekCornerGH** [dscalzi/HeliosLauncher#299]
[Default rss feed](https://helios-files.geekcorner.eu.org/rss.xml)
I commented lines causing the launcher to freeze. (dc:creator and slash:comments)

**Comment by dscalzi** [comment]
I'm unable to reproduce this. It looks like its working fine?

**Comment by GeekCornerGH** [comment]
Interesting, let me try later today
