### ISSUE TITLE
Respect official Electron security recommendation

### ISSUE THREAD

**Issue by Bricklou** [dscalzi/HeliosLauncher#302]
Hey !

I **higlhy** recommand you to check at the Electron [Security page](https://www.electronjs.org/docs/latest/tutorial/security), especially about theses 4 following points:
- [Do not enable Node.js integration for remote content](https://www.electronjs.org/docs/latest/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content)
- [Enable Context Isolation](https://www.electronjs.org/docs/latest/tutorial/security#3-enable-context-isolation)
- [Enable process sandboxing](https://www.electronjs.org/docs/latest/tutorial/security#4-enable-process-sandboxing)
- [Do not disable `webSecurity`](https://www.electronjs.org/docs/latest/tutorial/security#6-do-not-disable-websecurity)

The security of the user should be on the __top__ of your priority, but it seems currently a bit neglected on this part.

Thank you to take my comment in account for the good of your users. :slightly_smiling_face:

**Comment by dscalzi** [comment]
The problem with their security guidelines is that they want to leave the renderer totally inert. The developer experience is horrendous, having to create IPC bridges for even the most trivial syscall via electron itself or node itself.

If there are any serious concerns or attack vectors you wish to disclose feel free to private message me and I will take a look. I'm not particularly inclined to follow this guidance to the letter if there are no actual vulnerabilities.

This is not the first time I've reviewed their document, but unfortunately implementing a custom IPC protocol to wrap electron and node's APIs is kind of insane. It might be easier to design around it with a fresh codebase but it's a significant hinderance to redo an existing one.

**Comment by Bricklou** [comment]
> If there are any serious concerns or attack vectors you wish to disclose feel free to private message me and I will take a look.
Sure, care to share your Discord ID ? (i suppose you have once since the project has a Discord Server)

**Comment by Bricklou** [comment]
_Discussion finished on Discord_
