### ISSUE TITLE
[Project] Generalization for Third-Party

### ISSUE THREAD

**Issue by dscalzi** [dscalzi/HeliosLauncher#32]
This project was built for use on a specific server, as a result there are many hardcoded strings and features. My goal is to generalize the project and allow for easy customization. This is currently in the works, no ETA.

#### End Goals:
* Localization of strings to language files.
* External builder project which will patch all changes to the base project and invoke electron-builder. This will eliminate the need for users to change the base code.
* Full documentation.
* Vanilla launch configurations.

This list is not final. No ETA.

**Comment by Harjot1Singh** [comment]
Let me know how this is going, happy to help out!

**Comment by DarkScientist** [comment]
I'm very interested by this improvement, let me know if I can translate the strings in French!

**Comment by lukruh** [comment]
I would also be happy to help out here. I'm trying to customize the launcher for my self right now. I already started, translating to german and editing hard coded strings like discord links window titles etc.. 
Would it be useful to create a second json or yaml file to store all the customizations like urls logo title etc.. If you show me how you'd like the file to be structured and included I can create a PR.

**Comment by dscalzi** [comment]
This is more or less on hold for now. I am working on a rewrite (albeit slowly), and want to focus on that more. This can be looked at again when/if v1.x.x enters maintenance mode.

**Comment by lukruh** [comment]
alright, I'll have a look into the ts-refactor branch.. from time to time. This project is something I want to use to learn some js/electron basics, so will be nice to see how it develops :)
