### ISSUE TITLE
Crashes during installation when adding OptiFine mod

### ISSUE THREAD

**Issue by DontHopeZ** [dscalzi/HeliosLauncher#323]
When I configure the launcher and test it with the command "npm run start," the custom launcher starts successfully. After pressing "Play" and completing the file installation at 100%, Minecraft launches. However, after 1 second on the red Mojang screen where the mods are being downloaded, it shuts down. What could be the problem?

**Comment by GeekCornerGH** [comment]
Optifine is supposed to be added as a library, not a forge mod.

**Comment by DontHopeZ** [comment]
> Optifine is supposed to be added as a library, not a forge mod.

Thank you! I have an additional question. Do you happen to know a method for automatically applying a server resource pack or having resource pack files installed in the 'resourcepacks' folder take effect in-game immediately?

**Comment by GeekCornerGH** [comment]
You can force the resource pack on the server side
