### ISSUE TITLE
When automatically connecting to the server, automatically apply the server resource pack

### ISSUE THREAD

**Issue by DontHopeZ** [dscalzi/HeliosLauncher#324]
Hello. It seems you're facing an issue with server resource packs. When automatically connecting to the server, the option to install the server resource pack is prompted. After installing, the resource pack is applied correctly, but if you leave the server and come back, it asks again. How can I fix this issue?

**Comment by GeekCornerGH** [comment]
Try to reproduce on the official MC Launcher

**Comment by DontHopeZ** [comment]
> Try to reproduce on the official MC Launcher, it's seem to be an issue on your side/mojang side

Thank you for the response.
However, when selecting a server with the official launcher, changing the setting in the edit menu to "Server Resource Packs: Enabled" and connecting results in the server resource pack being installed without any prompts. On the other hand, when connecting with a custom launcher, it keeps asking whether to install the server resource pack even after it has been installed. In other words, if I turn it off and on again after installation, it keeps asking

**Comment by GeekCornerGH** [comment]
Are you by any luck using a mod like FancyMenu?

**Comment by DontHopeZ** [comment]
> Are you by any luck using a mod like FancyMenu to connect to the server?

I don't know what that is. I'm simply asking if it's possible to change the 'Server Resource Packs: Prompt' option to 'Server Resource Packs: Enabled' when connecting to the server using a custom launcher. If there's no way to do that, it seems like the only option is to keep pressing 'Enable' every time I exit and rejoin the server

**Comment by GeekCornerGH** [comment]
Probably misexplained myself, how is the player connecting to your server through the custom launcher? (eg 1. Open launcher, 2. Click Play, 3. Press Connect, 4. ???, 5. Enjoy)

**Comment by DontHopeZ** [comment]
> Probably misexplained myself, how is the player connecting to your server through the custom launcher? (eg 1. Open launcher, 2. Click Play, 3. Press Connect, 4. ???, 5. Enjoy)

It's in order from 1 -> 2 -> 5! As I mentioned, I configured it to connect directly to the server!

**Comment by GeekCornerGH** [comment]
Then a Mojang issue, since you're using autoconnect.

**Comment by DontHopeZ** [comment]
> Then a Mojang issue, since you're using autoconnect. This is not a Helios-related issue, so you'll want to close the issue.

Thank you!
