### ISSUE TITLE
Question about the redistributability.

### ISSUE THREAD

**Issue by foxypiratecove37350** [dscalzi/HeliosLauncher#332]
It's just a little question: can we make a non-open-source version and redistribute this non-open-source version?

**Comment by GeekCornerGH** [comment]
We used to disallow this, but the launcher is now under [MIT License](https://opensource.org/license/mit/) which afaik allows your usecase.
Disclaimer: I'm not a legal expert

**Comment by foxypiratecove37350** [comment]
I saw the license and It seems allow this but I wanted to ask you anyway to know if you allow me or not.

**Comment by foxypiratecove37350** [comment]
I have the answer now, so I will make my version 100% open-source before publishing and I will close this issue as completed.
