### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by ghost** [dscalzi/HeliosLauncher#334]
[Minecraft] Error: Could not find or load main class net.fabricmc.loader.impl.launch.knot.KnotClient
/tmp/.mount_MNetwoyBeIl2/resources/app.asar/app/assets/js/processbuilder.js:93 [Minecraft] Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient

**Comment by Krstf01** [comment]
I got the same issue, what was the solution?

**Comment by busybox11** [comment]
Same issue.
