### ISSUE TITLE
Build with macOS with a Macbook Air M2

### ISSUE THREAD

**Issue by Fairy-Jeux** [dscalzi/HeliosLauncher#337]
Hello, I want to build the launcher, but when I enter the command in the macOS console, I got this error message. Can some one help me please ?

**Comment by Fairy-Jeux** [comment]
I try with sudo, but he give me an error with the sign.

<img width="1470" alt="image" src="https://github.com/dscalzi/HeliosLauncher/assets/54899275/9fef4638-07ee-431c-9203-1bc84d1c2fc5">

**Comment by Fairy-Jeux** [comment]
My problem is resolved... The reason of the error is they didn't have the permission to modify in the cache.

**Comment by Codixer** [comment]
Your name is in the signage, I suggest removing the second pic
