### ISSUE TITLE
Why isn't my server list maintained?

### ISSUE THREAD

**Issue by why-tech** [dscalzi/HeliosLauncher#360]
![11](https://github.com/user-attachments/assets/36fbf3dd-af96-4534-8d2a-45f181367eca)

First of all, it's not very important, but when I run the mark through the server, the title gets Forge, so why is that?

When I connect to the Forge server, which is a sample in the Helios launcher, only the Minecraft* version comes out like this, but the title only shows the phrase Forge

I thought it was the difference in the server driver, so I switched the Forge, Paper, and Mohist servers and opened them, and they were all the same

And this is the most important thing. If you press PLAY through the launcher, the server is connected well at first, but after you connect, you come to the main through disconnection and enter the multiplayer, and you can't see the server list

If you turn off the mark and run it through the launcher again, the connection will be made

![22](https://github.com/user-attachments/assets/3b8a98fd-c6ce-4204-b156-8c8cdfa1aaea)

When I compared the Helios launcher distribution.json file with my file

{
"id": "servers.dat",
"name": "servers.dat",
"type": "File",
"artifact": {
"size": 80,
"url": "https://file path/servers.dat",
"MD5": "7b7e97178aaa06165d006b8f4ad92fb7",
"path": "servers.dat"
}
}

It's the same even though I put it in because of this

**Comment by Codixer** [comment]
My brain is losing cells, are you trying to add your servers to a server.dat file so it's in the multiplayer list?
