### ISSUE TITLE
no connect

### ISSUE THREAD

**Issue by seolmarin** [dscalzi/HeliosLauncher#363]
![image](https://github.com/user-attachments/assets/aa077eb1-8e2f-4feb-af0c-603404908491)
no connect launcher

**Comment by GeekCornerGH** [comment]
Your firewall might block the server files

**Comment by seolmarin** [comment]
> Your firewall might block the server files


Even if I turn off the firewall, it doesn't work.

**Comment by GeekCornerGH** [comment]
I can access the file itself just fine, unless you're using a custom  distribution.json?

**Comment by seolmarin** [comment]
I'm not sure

**Comment by seolmarin** [comment]
https://drive.google.com/file/d/1zfYTbNonjFdsVlqt98FJ1sLkKx8p2WF9/view?usp=drive_link  
Would you like to check if this link could be causing an error?

**Comment by GeekCornerGH** [comment]
Is your issue solved? What did you do to solve the issue? It might help people who will find this issue in the future
