### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by Escartem** [dscalzi/HeliosLauncher#39]
I modified _dev-app-update.yml_ so the launcher update from my repository. But every time I launch the app I get this error : 
`
A javascript error occurred in the main process
Uncaught Exception:
Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE
`

Error in the console : 

`
Initializing auto updater.
Checking for update
Error: HttpError: 404 Not Found
"method: GET url: https://github.com/Escartem/EscartemLauncher/releases/download/v0/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Mon, 11 Nov 2019 15:34:36 GMT",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "transfer-encoding": "chunked",
  "vary": "X-PJAX",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "F8D6:33B27:B4253D:10E78C0:5DC97F8B",
  "x-request-id": "185e71bb-2c6b-4eb5-acd0-ebcef86d85d9",
  "x-xss-protection": "1; mode=block"
}
    at createHttpError (C:\Users\Username\Desktop\Escartem-Launcher-2\node_modules\builder-util-runtime\out\httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (C:\Users\Username\Desktop\Escartem-Launcher-2\node_modules\builder-util-runtime\out\httpExecutor.js:167:14)
    at ClientRequest.<anonymous> (C:\Users\Username\Desktop\Escartem-Launcher-2\node_modules\builder-util-runtime\out\httpExecutor.js:133:16)
    at ClientRequest.emit (events.js:210:5)
    at URLRequest.<anonymous> (electron/js2c/browser_init.js:2376:12)
    at URLRequest.emit (events.js:210:5)
`

I only would like to update from github but maybe the error is caused by my repository because when dev-app-update.yml is with the default content it works but when I replace it with my repository it doesn’t work anymore.

**Comment by dscalzi** [comment]
1. Please either fork or at least clone the repository so that the commit history is preserved.
2. You're not doing something right. Electron-builder has documentation on how the updater works so I'm not going to explain it all here. The error is not difficult to read, the updater is looking for this file but it doesnt exist https://github.com/Escartem/EscartemLauncher/releases/download/v0/latest.yml.
