### ISSUE TITLE
Add the cracks in the launcher

### ISSUE THREAD

**Issue by MatthieuLeboeuf** [dscalzi/HeliosLauncher#41]
Hello,
would it be possible to add options for craks?

sorry for spelling, I'm french

Matthieu

**Comment by dscalzi** [comment]
No, I don't support cracked. The code is open source so if you want to use a different authentication system you can write that yourself.

**Comment by evernife** [comment]
@MatthieuLeboeuf if you still needs the offline mode...
https://github.com/FinalCraftMC/FinalCraft-Launcher/commit/7dbb43faa7c98becf9f2a093731eb5ba06c3ae32
