### ISSUE TITLE
How to install skin

### ISSUE THREAD

**Issue by Newserver-dev** [dscalzi/HeliosLauncher#42]
I used my system auth. How to install link-skin. Example: isset site http://website.com/skin.php?name=Mojang. Site return image full skin. how install? js

**Comment by dscalzi** [comment]
?

**Comment by Newserver-dev** [comment]
How can I set the minecraft skin through the launcher from the server?

**Comment by dscalzi** [comment]
That's not implemented in the launcher. You can do it with the mojang API. For changing the skin, I believe you need to have the security questions solved as well.

Example: https://github.com/starburn/node-mojang
