### ISSUE TITLE
Example distro json from twitch mod pack.

### ISSUE THREAD

**Issue by mrconnerton** [dscalzi/HeliosLauncher#44]
My community is interested in using this launcher for our servers. We have a few servers running some modpacks on it and would like to consolidate down to a single launcher.

I've having troubles understanding the documentation around the distribution.json. Do you think you could provide an example with some notes on how you made it if we wanted to use https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons for example? I think that would help a bunch of folks.

Thanks!

**Comment by dscalzi** [comment]
An example is here https://github.com/dscalzi/HeliosLauncher/blob/master/app/assets/distribution.json

**Comment by mrconnerton** [comment]
Thanks, I've seen the example and I've read the docs but its not very clear how to go from an existing modpack to that.

For example when I download the modpack from CF, it includes a manifest.json and a folder full of overrides.

Now I can probably figure out how to turn the forge and mods part together in the distribution.json but I don't know how the overrides fit in.

**Comment by mrconnerton** [comment]
As others have pointed out, this guy is actually an asshole and doesn't want to help.

"Just do it" he says.

Good luck with your project. Work on those people skills buddy.

**Comment by dscalzi** [comment]
I've told you what to do, write a conversion tool. My system is well documented.

**Comment by mrconnerton** [comment]
Just do it.
