### ISSUE TITLE
Why the mods aren't running?

### ISSUE THREAD

**Issue by GeekCornerGH** [dscalzi/HeliosLauncher#50]
Hello.
The launcher is very good but I have a difficulty. I added 2 mods in my file ["distribution.json"](https://github.com/GeekCornerGH/TitiMC-Launcher/blob/master/app/assets/distribution.json) 
Everything is fine, everything is downloading, but when Minecraft launches, the 2 additional mods do not activate. Nothing in the logs. Do you have an idea ?
Thanks in advance for your answer!
Have a good day !
GeekCorner

**Comment by TheCoolOne123** [comment]
Take a look at https://github.com/GeekCornerGH/TitiMC-Launcher/blob/master/docs/distro.md#liteloader

**Comment by TheCoolOne123** [comment]
You will see that there are 2 values in the distribution.json

**Comment by GeekCornerGH** [comment]
Can you commit to my repository?

**Comment by TheFlash787** [comment]
@GeekCornerGH Ensure that in your `distribution.json`, you have set it up so that the mods you want to be enabled are set as required.

**Comment by GeekCornerGH** [comment]
@TheFlash787 Mods are required in distribution.json! They are downloaded but not executed.

**Comment by GeekCornerGH** [comment]
Resolved. Thanks @TheFlash787 and @TheCoolOne123 for helping. I think I missed the "def" value. Have a good day !

**Comment by dscalzi** [comment]
For future reference.. https://github.com/dscalzi/HeliosLauncher/blob/master/docs/distro.md#required-object

**Comment by TheCoolOne123** [comment]
> Resolved. Thanks @TheFlash787 and @TheCoolOne123 for helping. I think I missed the "def" value. Have a good day !

Yeah, no problem. Always happy to help :)
