### ISSUE TITLE
Developer Mode - Stuck on loadingContent

### ISSUE THREAD

**Issue by TheCherry** [dscalzi/HeliosLauncher#51]
The Launcher sometimes stuck in the loadingContent view and there is no error in the console and the network tab don't show anything special.

Sometimes is loading correct and sometimes not.

```
[Preloader] Loading..
C:\Users\x\Documents\HeliosOrg\app\assets\js\loggerutil.js:9 [ConfigManager] Successfully Loaded
C:\Users\x\Documents\HeliosOrg\app\assets\js\loggerutil.js:9 [Preloader] Cleaned natives directory.
C:\Users\x\Documents\HeliosOrg\app\assets\js\loggerutil.js:9 [Preloader] Loaded distribution index.
C:\Users\x\Documents\HeliosOrg\app\assets\js\loggerutil.js:9 [Landing] Refreshing Mojang Statuses..
C:\Users\x\Documents\HeliosOrg\app\assets\js\loggerutil.js:9 [UICore] UICore Initializing..
```

![grafik](https://user-images.githubusercontent.com/1090782/75126580-edb21c00-56ba-11ea-98b8-76b06e597718.png)

**Comment by VolanDeVovan** [comment]
It because ipc send distributionindex to main process before the listener is registered
