### ISSUE TITLE
Problem when launching the game

### ISSUE THREAD

**Issue by evanlegamer** [dscalzi/HeliosLauncher#52]
Hi, i have like 10 peoples stuck in this problem, i don't know why

`[AEx] Invalid or unsupported zip format. No END header found
[LaunchSuite] AssetExec exited with code 1, assuming error.`

At first I thought it was my 'distribution.json' problem. However I made tests with these users who had this problem by making them a distribution.json with only Forge hosted at this address: http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2 -14.23.5.2836 / forge-1.12.2-14.23.5.2836-universal.jar
and they still had the same problem without being able to understand why.

Thank you in advance for your help.

This is full log : 

> C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [Preloader] Loading..
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [ConfigManager] Successfully Loaded
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [Preloader] Cleaned natives directory.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [Landing] Refreshing Mojang Statuses..
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [UICore] UICore Initializing..
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [Preloader] Loaded distribution index.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [AutoUpdater] Initializing..
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [Landing] Refreshing Server Status
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [AutoUpdater] Checking for update..
app.ejs:1 A cookie associated with a cross-site resource at https://github.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:17 [Landing] Object
warn @ C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:17
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [AuthManager] Account access token validated.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [AutoUpdater] No new update found.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [Landing] Launching game..
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\assetguard.js:440 string
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\assetguard.js:390 java.runtime.version = 1.8.0_241-b07
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\assetguard.js:380 sun.arch.data.model = 64
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [Landing] Java version meta Object
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [Landing] Refreshing Server Status
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [AEx] AssetExec Started
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [AEx] [ConfigManager] Successfully Loaded
[DistroManager] Developer mode disabled.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [LaunchSuite] Validated distibution index.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [LaunchSuite] Version data loaded.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:17 [Landing] Object
warn @ C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:17
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [LaunchSuite] Asset Validation Complete
uicore.js:29 Ne regardez pas la console si on ne vous l'a pas demandé
uicore.js:30 If you've been told to paste something here, you're being scammed.
uicore.js:31 Unless you know exactly what you're doing, close this window.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [LaunchSuite] Library validation complete.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [LaunchSuite] File validation complete.
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [AEx] 
C:\Program Files\MazeLauncher
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [AEx] \resources\app.asar\node_modules\adm-zip\zipFile.js:107
			throw Utils.Errors.INVALID_FORMAT;
			^
I
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [AEx] nvalid or unsupported zip format. No END header 
C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:9 [AEx] found

> C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:25 [LaunchSuite] AssetExec exited with code 1, assuming error.
> error @ C:\Program Files\MazeLauncher\resources\app.asar\app\assets\js\loggerutil.js:25
(anonymous) @ landing.js:527
emit @ events.js:210
maybeClose @ internal/child_process.js:1021
ChildProcess._handle.onexit @ internal/child_process.js:283
DevTools failed to parse SourceMap: file:///C:/Program%20Files/MazeLauncher/resources/app.asar/app/uri.all.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/MazeLauncher/resources/app.asar/app/performance-now.js.map

**Comment by Dunklheit** [comment]
@evanlegamer 
invalid or unsupported zip format. No END header
This can be because:
1) You are using dropbox, mediafire, or other similar services where a direct file download isn't possible
2) Your zip file is corrupt
3) You are trying to download something that isn't a zip file as a zip file

As far as what you need to know .jars are also zip files

**Comment by Dunklheit** [comment]
@dscalzi You can close this one, as it appears to be an enduser fault
