### ISSUE TITLE
Add Non Premium Login For MCL

### ISSUE THREAD

**Issue by SezarMoein** [dscalzi/HeliosLauncher#54]
this is a amazing launcher but can we make users logined to our server without Minecraft Premium Account?
because in our server all players has no premium account from minecraft and they play with Tlauncher that make them login without any user and password of minecraft hub and users can login to the servers just with a NickName
so how can we do login without any check of minecraft hub?

**Comment by evanlegamer** [comment]
i did this by creating an yggdrasil authentification server

**Comment by dscalzi** [comment]
As mentioned before, I don't support cracked.

**Comment by SezarMoein** [comment]
we cant use both of them can you update mazeLauncher to a non premium Versoin 
it means if you add a function like Local=false for use the mojang server or non premium server in config files we can use this amazing launcher better

**Comment by TheFlash787** [comment]
> 
> 
> we cant use both of them can you update mazeLauncher to a non premium Versoin
> it means if you add a function like Local=false for use the mojang server or non premium server in config files we can use this amazing launcher better

It's not a case of him not being able to implement it, or that it's not possible. @dscalzi has already mentioned that he doesn't *support* his launcher being used for cracked clients, hence why he won't work towards making it possible.

If you want to allow cracked users to use this launcher, you'll need to fork the launcher and develop your own layer to make that possible. @SezarMoein
