### ISSUE TITLE
Trying to understand how forge is installed

### ISSUE THREAD

**Issue by tartiflm** [dscalzi/HeliosLauncher#57]
Hello !

In an objective to use this launcher for one of my projects, I'm trying to understand how Forge is intalled.

... However, after many hours of search through the code, I still don't understand where it's happening.

Could you take 10-15 minutes to explain precisely how your machinery works ? Thank you in advance 😅

**Comment by dscalzi** [comment]
I'll link you to the key parts of the code, just follow the method calls.

1. https://github.com/dscalzi/HeliosLauncher/blob/9d1aa497a7285f7c939608cb9c77fdac2a652d55/app/assets/js/assetguard.js#L1839
2. https://github.com/dscalzi/HeliosLauncher/blob/master/app/assets/js/processbuilder.js#L37
