### ISSUE TITLE
1.15.2

### ISSUE THREAD

**Issue by MHProDev** [dscalzi/HeliosLauncher#64]
Plasse Help Me For Add MineCraft 1.15.2 In Launcher

**Comment by dscalzi** [comment]
You can ask for support on the discord as well. You can either manually setup a 1.15.2 distribution.json or use [Nebula](https://github.com/dscalzi/Nebula) to set one up for you.

A user has created a pretty good guide for how to use Nebula incase you want to follow some instructions. https://github.com/DNSJS/HeliosTutorials/blob/master/CreateNebulaDistro.md
