### ISSUE TITLE
Does not load if minecraft is already running

### ISSUE THREAD

**Issue by jakeau** [dscalzi/HeliosLauncher#66]
Unable to launch minecraft if minecraft is already running, even if on a different account :)

Is there a way around this?

**Comment by Ignant** [comment]
Please explain more, as I can launch 3 separate instances (as i am an admin on a server that has 3 different packs loaded) on 1 account, I can not play on all 3 but can have the clients open for all for a quick swap between servers

**Comment by dscalzi** [comment]
I think you're talking about the launch area not toggling. Fixed in https://github.com/dscalzi/HeliosLauncher/commit/71b25d3e5c2932c1e0f4dc58f3659f7b661fb73a
