### ISSUE TITLE
Install Path / Data Directory not actual

### ISSUE THREAD

**Issue by Ignant** [dscalzi/HeliosLauncher#67]
When doing an install and say you change the default to the D: drive it does create a directory with some files... But will still add files to 

> C:\Users\marke\AppData\Roaming\launcherName

> C:\Users\marke\AppData\Roaming\.launcherName

If you access the launcher and go to Settings > Launcher > and select Choose Folder you can select a directory but the GUI does not change nor does the config.json located in Roaming\LauncherName.

Very misleading and frustrating to end users.

I have gone through a bit of the files and cant find where it is calling to make/set these paths to assist in getting it corrected.

**Comment by dscalzi** [comment]
The application is installed to the D drive, however the configuration files will be stored in your `userData` folder. The application **requires** a predictable location to look for files, hence why this cannot be changed. There is roughly 10MB of configuration data there (most of it internal to electron), so I hardly see it as a problem. The launcher gives you an option to change where you want to install the game to.

That being said, it appears that for some reason the UI is not updating the path. This is just another instance where something breaks after a certain period of time. I will have to debug it to see why it suddenly stopped working.

**Comment by dscalzi** [comment]
Appears to be a breaking change with electrom 7.. investigating a fix. https://www.electronjs.org/docs/breaking-changes#behavior-changed-webkitdirectory-attribute-for-input-typefile-now-lists-directory-contents
