### ISSUE TITLE
Latest Forge 1.12 builds change .json structure

### ISSUE THREAD

**Issue by Dunklheit** [dscalzi/HeliosLauncher#69]
I have recently forked Helios Launcher to add my community's modpack to, but when using Forge 1.12.2-14.23.5.2854 Helios was unable to start Minecraft. Dev console makes mention to version.json changing as Forge version reports `null`. Using 1.12.2-14.23.5.2847 works as expected.

**Comment by dscalzi** [comment]
Fixed in https://github.com/dscalzi/HeliosLauncher/issues/73
