### ISSUE TITLE
Auto-Connect fails on 1.15.2 Forge

### ISSUE THREAD

**Issue by Dunklheit** [dscalzi/HeliosLauncher#74]
Auto-Connect fails when launching 1.15.2 without any reportable errors. Game simply launches to main menu. Perhaps a command line argument has changed?

**Comment by dscalzi** [comment]
Might not be possible anymore.

**Comment by dscalzi** [comment]
Looks like it's crashing on 1.15.2 if I pass the --server and --port arguments. Not sure if this is a bug with minecraft or with forge.

**Comment by dscalzi** [comment]
Fixed for 1.13 and 1.14. Passing the arguments on 1.15 is causing an OpenGL exception so I've disabled it on that version for now. https://github.com/dscalzi/HeliosLauncher/commit/1bdb413ab5a64958f2c14f410fa40fcd2db0c9da

**Comment by dscalzi** [comment]
Should be fixed. Please upgrade your forge to `≥ 31.2.15`
