### ISSUE TITLE
Rich Presence remains frozen on "Loading game .."

### ISSUE THREAD

**Issue by NhProGamer** [dscalzi/HeliosLauncher#80]
![Capture](https://user-images.githubusercontent.com/44909803/85519872-748fea80-b602-11ea-8595-86627becf4fa.PNG)
Rich Presence remains frozen on "Loading game .."
:/

**Comment by dscalzi** [comment]
For what version of Minecraft?

**Comment by NhProGamer** [comment]
1.9.4

**Comment by dscalzi** [comment]
So this is kind of guesswork for some versions of the game. All we're doing is monitoring stdout for a certain string which will signify that we're at a specific phase of the load lifecycle. These strings may even change within versions of the game. For now I'll switch it to look for `Sound engine started` as that seems pretty standard across versions.
