### ISSUE TITLE
Resolution issues

### ISSUE THREAD

**Issue by lukasdeveloper** [dscalzi/HeliosLauncher#81]
Hello,

whatever resolution you set in the game settings of the launcher it does not apply. I am using a 4k monitor and its always 1920x1017, when i go in fullscreen it fully breaks as example: https://lukasdev.xyz/ss/449ch7F449b1c1.png
This is a screenshot of the whole screen, its basically cut off.

I am not sure why that happends but a solution would be that the game fits to the resolution where the launcher is located on. (Monitor)

Forge: 1.12.2-14.23.5.2847

Kind Regards

**Comment by dscalzi** [comment]
Is this fixed @lukasdeveloper ?

**Comment by lukasdeveloper** [comment]
Looks like it only happens on my pc for whatever reason, so yes :D
