### ISSUE TITLE
Travis upload github

### ISSUE THREAD

**Issue by luuxis** [dscalzi/HeliosLauncher#82]
make sure that when we use Travis to build it upload to github

**Comment by jordanamr** [comment]
Unrelated.
Please see the [Travis documentation](https://docs.travis-ci.com/user/deployment/releases/)

**Comment by GeekCornerGH** [comment]
> make sure that when we use Travis to build it upload to github

First, creates a Release on GitHub. You can put whatever you want in the name and description, but be sure that the tag is made up of `vx.x.x` by replacing x with the version registered in the package.json. Then press `save draft`, not publish.
Push commits on GitHub, then check your travis page.
After the build is done, just refresh the release draft page. Check that the files `latest.yml`,` x.blockmap` and the installers (exe, dmg, and appimage) are uploaded then publish the release.
You're done 😀
