### ISSUE TITLE
Files downloading after every launch

### ISSUE THREAD

**Issue by DraZiiXx** [dscalzi/HeliosLauncher#83]
Hello,
Sorry in advance if i have bad english, i will try to make myself understandable.
So my problem is that when i launch my launcher it launches perfectly, my distribution.json works fine, but when i relaunch it, it downloads every file again and i dont know why, and i wanted to ask if i can have some help?
Thank you in advance
DraZIiXx

**Comment by dscalzi** [comment]
Post the distribution?

**Comment by DraZiiXx** [comment]
[http://revivepcm.fr/revive/distribution.json](url)

**Comment by dscalzi** [comment]
You're specifying sha1 hashes. They must be MD5. See https://github.com/dscalzi/HeliosLauncher/blob/master/docs/distro.md

**Comment by dscalzi** [comment]
And the md5 hashes must be lowercase.

**Comment by DraZiiXx** [comment]
Thank you very much !
