### ISSUE TITLE
Unable to read any generated distribution file

### ISSUE THREAD

**Issue by ReburonMaxus98** [dscalzi/HeliosLauncher#84]
hello i ran into a problem that anytime i replace the distribution.json file in the js folder launcher doesnt load and gets stuck in a loading loop i tried the default distribution file and it works but i used the tool profived for generation of distribution.json file and even after multiple tries of changing and re-generation of the file it still doesnt work,after using the ctrl+shift+i combination i got only these errors:
***
C:\Users\MyName\Desktop\developmentuwu\Helios-pan\app\assets\js\loggerutil.js:9 [Preloader] Failed to load distribution index.
C:\Users\MyName\Desktop\developmentuwu\Helios-pan\app\assets\js\loggerutil.js:25 [Preloader] Error: getaddrinfo ENOTFOUND cdn.superkooka.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60)
error @ C:\Users\Bread\Desktop\developmentuwu\Helios-pan\app\assets\js\loggerutil.js:25
C:\Users\MyName\Desktop\developmentuwu\Helios-pan\app\assets\js\loggerutil.js:9 [Preloader] Attempting to load an older version of the distribution index.
app.ejs:1 Uncaught SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\MyName\Desktop\developmentuwu\Helios-pan\app\assets\js\distromanager.js:577
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61)
***
and these warnings :
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/MyName/Desktop/developmentuwu/Helios-pan/app/uri.all.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/MyName/Desktop/developmentuwu/Helios-pan/app/performance-now.js.map: 

if it can help in any way i attach the latest distribution.json file :
[The Distribution.json file ](http://s1r9tbckp.jecool.net/Test/TestNewBeta/distribution.json)

**Comment by dscalzi** [comment]
```
C:\Users\MyName\Desktop\developmentuwu\Helios-pan\app\assets\js\loggerutil.js:25 [Preloader] Error: getaddrinfo ENOTFOUND cdn.superkooka.com
```

The link to your remote copy is likely wrong.

**Comment by dscalzi** [comment]
Further, I don't know why people keep trying to put the distribution into the js folder..

https://github.com/dscalzi/HeliosLauncher/blob/master/app/assets/js/distromanager.js#L540
