### ISSUE TITLE
Got NaN bytes from something.txt

### ISSUE THREAD

**Issue by lucasboss45** [dscalzi/HeliosLauncher#87]
![image](https://user-images.githubusercontent.com/29255472/87830289-0812af00-c881-11ea-85d9-c6e7f13b27bd.png)

**Comment by dscalzi** [comment]
Please put more effort into this report.

**Comment by lucasboss45** [comment]
Well all I can tell you is that my OS is Windows 10, then again there isn't exactly a bug report template nor do I know what kind of information would be relevent for this type of report.

**Comment by lucasboss45** [comment]
I fixed it myself.
