### ISSUE TITLE
Question about the forge client jar

### ISSUE THREAD

**Issue by lucasboss45** [dscalzi/HeliosLauncher#89]
Hello, so I have a friend of a mine that let me know it would technically be illegal to redistribute the Forge client jars according to the Minecraft EULA. However the forge jars are packaged by Nebula in the distribution.

"If you've bought the Game, you may play around with it and modify it by adding modifications, tools, or plugins, which we will refer to collectively as "Mods." By "Mods," we mean something original that you or someone else created that doesn't contain a substantial part of our copyrightable code or content. When you combine your Mod with the Minecraft software, we will call that combination a "Modded Version" of the Game. We have the final say on what constitutes a Mod and what doesn't. **You may not distribute any Modded Versions of our Game or software**, and we’d appreciate it if you didn’t use Mods for griefing. Basically, Mods are okay to distribute; hacked versions or **Modded Versions of the Game client or server software are not okay to distribute.**" - Minecraft EULA

Now because I run a server and use this software It'd be nice to get that changed somehow. And also it might help you not get into trouble in the future

**Comment by dscalzi** [comment]
By that logic this website is not allowed https://files.minecraftforge.net/

**Comment by lucasboss45** [comment]
Not really because the way Minecraft Forge functions is they use the vanilla minecraft version already installed on your machine and patches and recompiles it, Minecraft Forge only distributes patches so that they recompile Minecraft on your machine, they don't distribute a jar with minecraft code with it. However with the way the distributions work the Forge client jar which gets packaged by Nebula does contain minecraft code. A way to get around this would be to make Forge install itself on the client's machine automatically.
