### ISSUE TITLE
[LaunchSuite] Error during validation:

### ISSUE THREAD

**Issue by Djnebertoze** [dscalzi/HeliosLauncher#99]
Hello !
I'm a small French developper and i have a problem when i want launch the game :/
![image](https://user-images.githubusercontent.com/60182839/91294563-08646b00-e79a-11ea-8f1d-8b8286b75b5c.png)
Help me please !

**Comment by TheFlash787** [comment]
Hey! Currently there really isn't much we can do with this. We'll need some more information.

Please can you right click on your log and 'save as'. Afterwards you should be able to drop that .log file into here so we can see what's happening.

What are you seeing when this happens? Does the pack launch? What's the percentage?

Also, please can we see the fork that you're using. If you've changed anything, there'll be very little we can do without knowing what has changed.

Thanks

**Comment by Djnebertoze** [comment]
[-1598438963478.log](https://github.com/dscalzi/HeliosLauncher/files/5129307/-1598438963478.log)
This is the log

**Comment by Djnebertoze** [comment]
![image](https://user-images.githubusercontent.com/60182839/91295087-cf78c600-e79a-11ea-8334-9dd4f755f25c.png)

**Comment by Djnebertoze** [comment]
The repo is: https://github.com/azgariopi/Aprabrica

**Comment by dscalzi** [comment]
@Djnebertoze Can you please expand the `error` in the **Error During Validation** message?
